### ISSUE TITLE
Docker Login Failure

### ISSUE THREAD

**Issue by akamalov** [StehlikC/docker-ci-demo#1]
Hey Casey,

Thanks so much for the tutorial. So far all instructions were very clear. Getting into a problem with CircleCI build, and I think I am missing something. The error is:

```
docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
flag needs an argument: -p

docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS returned exit code 2

See 'docker login --help'. Action failed: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

```

My circle.yml file is no different than you have in your repository:

```
machine:
  python:
    version: 2.7.3
  services:
    - docker

dependencies:
  pre:
    - pip install awscli
    - docker build -t stehlikc/docker-ci-demo:$CIRCLE_SHA1 .

test:
  override:
    - docker run stehlikc/docker-ci-demo:$CIRCLE_SHA1 rspec

deployment:
  production:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - ./scripts/deploy.sh $CIRCLE_SHA1
```

Any pointers??

Thanks again,

Alex
